version: '3.3'
services:
  reflow_web_front:
    platform: linux/x86_64 
    build: .
    command: bash -c "npm run web:build && npm run web:start"
    environment:
      - CONFIG=development
    volumes:
      - .:/code
    ports:
      - "3000:3000"