version: '3.3'
services:
  reflow_web_front:
    build: .
    command: npm run web:dev
    environment:
      - CONFIG=development
      - API_HOST=https://reflow-server-to-front-staging.xpdufpbcds.us-east-1.elasticbeanstalk.com/
    volumes:
      - .:/code
    ports:
      - "3000:3000"