export const AUTHENTICATE = 'AUTHENTICATE';
export const DEAUTHENTICATE = 'DEAUTHENTICATE';
export const ERROR = 'ERROR';
export const GET_FORMS = 'GET_FORMS';
export const UPDATE_GROUPS = 'UPDATE_GROUPS';
export const GET_FORMULARY = 'GET_FORMULARY';