import login from "../../redux/actions/login"

const strings = {
    'pt-br': {
        indexPageTitle: 'Reflow',
        loginPageTitle: 'Login - Reflow',
        emailLoginLabel: 'E-mail',
        passLoginLabel: 'Senha',
        submitButtonLabel: 'Entrar',
        incorrectPassOrUserError: 'Login e/ou senha incorretos',
        managementPageTitle: 'Gestão - Reflow',
        disabledGroupLabel: 'O Grupo está desativado',
        disabledFormLabel: 'O Formulário está desativado',
        addNewFormButtonLabel: 'Adicionar novo formulário',
        sidebarEditTemplateButtonLabel: 'Editar templates',
        sidebarAddNewTemplateButtonLabel: 'Adicionar novo',
        goBack: 'Voltar',
        calendarMonthReferenceJanuary: 'Janeiro',
        calendarMonthReferenceFebruary: 'Fevereiro',
        calendarMonthReferenceMarch: 'Março',
        calendarMonthReferenceApril: 'Abril',
        calendarMonthReferenceMay: 'May',
        calendarMonthReferenceJune: 'Junho',
        calendarMonthReferenceJuly: 'Julho',
        calendarMonthReferenceAugust: 'Agosto',
        calendarMonthReferenceSeptember: 'Setembro',
        calendarMonthReferenceOctober: 'Outubro',
        calendarMonthReferenceNovember: 'Novembro',
        calendarMonthReferenceDecember: 'Dezembro',
        calendardayOfTheWeekReferenceSunday: 'Dom',
        calendardayOfTheWeekReferenceMonday: 'Seg',
        calendardayOfTheWeekReferenceTuesday: 'Ter',
        calendardayOfTheWeekReferenceWednesday: 'Qua',
        calendardayOfTheWeekReferenceThursday: 'Qui',
        calendardayOfTheWeekReferenceFriday: 'Sex',
        calendardayOfTheWeekReferenceSaturday: 'Sáb',
        headerGestaoLabel: 'Gestão',
        headerDashboardLabel: 'Dashboard',
        headerSettingsLabel: 'Configurações',
        headerRefferalLabel: 'Indicar usuários',
        headerCompanyLabel: 'Empresa',
        headerChangeDataLabel: 'Alterar Dados',
        headerBillingLabel: 'Pagamento',
        headerNotificationLabel: 'Notificações',
        headerHelpLabel: 'Ajuda',
        formularyFieldAttachmentDefaultLabel: 'Clique ou arraste arquivos aqui'
    }
}

export default strings